// Code generated by DeltaDatabase manual proto generator. DO NOT EDIT.
// source: worker.proto

package proto

// SubscribeRequest is sent by a Processing Worker to register with the Main Worker.
type SubscribeRequest struct {
	WorkerId string            `json:"worker_id,omitempty"`
	Pubkey   []byte            `json:"pubkey,omitempty"`
	Tags     map[string]string `json:"tags,omitempty"`
}

// GetWorkerId returns the worker id.
func (x *SubscribeRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

// GetPubkey returns the public key bytes.
func (x *SubscribeRequest) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

// GetTags returns the worker tags map.
func (x *SubscribeRequest) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// SubscribeResponse is returned by the Main Worker after registration.
type SubscribeResponse struct {
	Token      string `json:"token,omitempty"`
	WrappedKey []byte `json:"wrapped_key,omitempty"`
	KeyId      string `json:"key_id,omitempty"`
}

// GetToken returns the token.
func (x *SubscribeResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// GetWrappedKey returns the wrapped key.
func (x *SubscribeResponse) GetWrappedKey() []byte {
	if x != nil {
		return x.WrappedKey
	}
	return nil
}

// GetKeyId returns the key id.
func (x *SubscribeResponse) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

// ProcessRequest requests a GET or PUT operation on an entity.
type ProcessRequest struct {
	DatabaseName string `json:"database_name,omitempty"`
	EntityKey    string `json:"entity_key,omitempty"`
	SchemaId     string `json:"schema_id,omitempty"`
	Operation    string `json:"operation,omitempty"`
	Payload      []byte `json:"payload,omitempty"`
	Token        string `json:"token,omitempty"`
}

// GetDatabaseName returns the database name.
func (x *ProcessRequest) GetDatabaseName() string {
	if x != nil {
		return x.DatabaseName
	}
	return ""
}

// GetEntityKey returns the entity key.
func (x *ProcessRequest) GetEntityKey() string {
	if x != nil {
		return x.EntityKey
	}
	return ""
}

// GetSchemaId returns the schema id.
func (x *ProcessRequest) GetSchemaId() string {
	if x != nil {
		return x.SchemaId
	}
	return ""
}

// GetOperation returns the operation.
func (x *ProcessRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

// GetPayload returns the payload.
func (x *ProcessRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// GetToken returns the token.
func (x *ProcessRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// ProcessResponse returns the operation result or error.
type ProcessResponse struct {
	Status  string `json:"status,omitempty"`
	Result  []byte `json:"result,omitempty"`
	Version string `json:"version,omitempty"`
	Error   string `json:"error,omitempty"`
}

// GetStatus returns the status string.
func (x *ProcessResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// GetResult returns the result bytes.
func (x *ProcessResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

// GetVersion returns the version string.
func (x *ProcessResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// GetError returns the error string.
func (x *ProcessResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}
