// Code generated by DeltaDatabase manual proto generator. DO NOT EDIT.
// source: worker.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// MainWorkerClient is the client API for MainWorker service.
type MainWorkerClient interface {
	// Subscribe registers a Processing Worker and returns a token and wrapped key material.
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (*SubscribeResponse, error)
	// Process performs internal GET/PUT operations for database entities.
	Process(ctx context.Context, in *ProcessRequest, opts ...grpc.CallOption) (*ProcessResponse, error)
}

type mainWorkerClient struct {
	cc grpc.ClientConnInterface
}

// NewMainWorkerClient creates a new MainWorker client.
func NewMainWorkerClient(cc grpc.ClientConnInterface) MainWorkerClient {
	return &mainWorkerClient{cc}
}

func (c *mainWorkerClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (*SubscribeResponse, error) {
	out := new(SubscribeResponse)
	err := c.cc.Invoke(ctx, "/deltadb.MainWorker/Subscribe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainWorkerClient) Process(ctx context.Context, in *ProcessRequest, opts ...grpc.CallOption) (*ProcessResponse, error) {
	out := new(ProcessResponse)
	err := c.cc.Invoke(ctx, "/deltadb.MainWorker/Process", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MainWorkerServer is the server API for MainWorker service.
type MainWorkerServer interface {
	// Subscribe registers a Processing Worker and returns a token and wrapped key material.
	Subscribe(context.Context, *SubscribeRequest) (*SubscribeResponse, error)
	// Process performs internal GET/PUT operations for database entities.
	Process(context.Context, *ProcessRequest) (*ProcessResponse, error)
}

// UnimplementedMainWorkerServer provides forward-compatible implementations.
type UnimplementedMainWorkerServer struct{}

// Subscribe returns unimplemented by default.
func (UnimplementedMainWorkerServer) Subscribe(context.Context, *SubscribeRequest) (*SubscribeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}

// Process returns unimplemented by default.
func (UnimplementedMainWorkerServer) Process(context.Context, *ProcessRequest) (*ProcessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Process not implemented")
}

// RegisterMainWorkerServer registers the MainWorkerServer to a gRPC server.
func RegisterMainWorkerServer(s grpc.ServiceRegistrar, srv MainWorkerServer) {
	s.RegisterService(&MainWorker_ServiceDesc, srv)
}

func _MainWorker_Subscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainWorkerServer).Subscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/deltadb.MainWorker/Subscribe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainWorkerServer).Subscribe(ctx, req.(*SubscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainWorker_Process_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainWorkerServer).Process(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/deltadb.MainWorker/Process",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainWorkerServer).Process(ctx, req.(*ProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MainWorker_ServiceDesc is the grpc.ServiceDesc for MainWorker service.
var MainWorker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "deltadb.MainWorker",
	HandlerType: (*MainWorkerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Subscribe",
			Handler:    _MainWorker_Subscribe_Handler,
		},
		{
			MethodName: "Process",
			Handler:    _MainWorker_Process_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "worker.proto",
}
